import { v4 as uuidv4 } from 'uuid';
export  const Movies=[
    
    {id: uuidv4(),    title:"Mulan",    description:"Mulan is a 2020 American fantasy action drama film produced by Walt Disney Pictures. ... The plot takes place in Imperial China, where Hua Mulan, the eldest daughter of an honored warrior, masquerades as a man to take her ailing father's place during a general conscription .",                                                         posterURL:"https://upload.wikimedia.org/wikipedia/en/1/17/Mulan_%282020_film%29_poster.jpg",                                                    rating:2, trailer:"https://www.youtube.com/embed/KK8FHdFluOQ" },
    {id: uuidv4(),    title:"Maleficent",                                 description:"Maleficent is a powerful fairy living in the Moors, a magical forest realm bordering a human kingdom. As a young girl, Maleficent meets and falls in love with a human peasant boy named Stefan. ... His love is overshadowed by ambition, and as they grow older, the two grow apart and Maleficent .",    posterURL:"https://i.dawn.com/primary/2019/12/5df14760743a6.jpg",                                                                               rating:4,trailer:"https://www.youtube.com/embed/n0OFH4xpPr4" },
    {id: uuidv4(),    title:"Joker",                                           description:"Arthur Fleck, a party clown, leads an impoverished life with his ailing mother. However, when society shuns him and brands him as a freak, he decides to embrace the life of crime and chaos.",                                                                                                        posterURL:"https://i.egycdn.com/pic/WmFwZndlY21MTnZtYm1qbWptYWN4dmNtam1tbW13VG1tYg.jpg",                                                        rating:3,trailer:"https://www.youtube.com/embed/zAGVQLHvwOY"},
    {id: uuidv4(),    title:"Brave",                                   description:"Set in the Scottish Highlands, the film tells the story of Princess Merida of DunBroch who defies an age-old custom, causing chaos in the kingdom by expressing the desire not to be betrothed. ... Brave is the first film to use . ",                                                                        posterURL:"https://upload.wikimedia.org/wikipedia/en/9/96/Brave_Poster.jpg",                                                                    rating:5,trailer:"https://www.youtube.com/embed/TEHWDA_6e3M"},
    {id: uuidv4(),    title:"The Dark Knight ",                                description:"After Gordon, Dent and Batman begin an assault on Gotham's organised crime, the mobs hire the Joker, a psychopathic criminal mastermind who offers to kill Batman and bring the city to its knees.",                                                                                                   posterURL:"https://i.egycdn.com/pic/WmFwZndlY21FbW1tYm1ibXVjbWptVElhY05md1A.jpg",                                                               rating:4,trailer:"https://www.youtube.com/embed/EXeTwQWrcwY"},
    {id: uuidv4(),    title:"Frozen II",                                       description:"Set three years after the events of the first film, the story follows Elsa, Anna, Kristoff, Olaf, and Sven, who embark on a journey beyond their kingdom of Arendelle in order to discover the origin of Elsa's magical powers and save their kingdom after a mysterious voice calls out to Elsa.",    posterURL:"https://etbilarabi.com/sites/default/files/styles/article_landing/public/2019-11/a795cfabc3f07fd25effc0e9da0e50d0.png?itok=pofDL71A",rating:3.5,trailer:"https://www.youtube.com/embed/Zi4LMpSDccc"},
]
